name: "Tag & Deploy Action"

on:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test action

    steps:
      - uses: actions/checkout@v1
        name: Checkout code

      - uses: r0adkll/sign-android-release@v1
        name: Sign APK
          # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
          alias:  ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword:  ${{ secrets.SIGNING_KEY_PASSWORD }}
          keyPassword:  ${{ secrets.SIGNING_KEY_PASSWORD }}

      # Example use of `signedReleaseFile` output -- not needed
      - uses: actions/upload-artifact@v2
        with:
          name: Signed app bundle
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

      #4
      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          generate_release_notes: true
          prerelease: true
          files: |
            ${{steps.sign_app.outputs.signedReleaseFile}}