name: "Tag & Deploy Action"

on:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test action

    steps:
      - uses: actions/checkout@v1
        name: Checkout code

      - uses: ./
        name: Sign APK
        with:
          releaseDirectory: app/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
          alias: secrets.SIGNING_KEY_ALIAS
          keyStorePassword: secrets.SIGNING_STORE_PASSWORD
          keyPassword: SIGNING_KEY_PASSWORD

  release:
    needs: test
    runs-on: ubuntu-latest
    name: Update action

    steps:
      - uses: actions/checkout@v1
        name: Checkout code

      - name: Update v1 Tag
        uses: hole19/git-tag-action@master
        env:
          TAG: v1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}