name: "Tag & Deploy Action"

on:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test action

    steps:
      - uses: actions/checkout@v1
        name: Checkout code

      - uses: r0adkll/sign-android-release@v1
        name: Sign APK
        with:
          releaseDirectory: app/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
          alias: secrets.SIGNING_KEY_ALIAS
          keyStorePassword: secrets.SIGNING_STORE_PASSWORD
          keyPassword: SIGNING_KEY_PASSWORD